config/routes.rb
Rails.application.routes.draw do
  root "home#index", via: :get 
  devise_for :users , controllers: {
  sessions: 'users/sessions'
  }
  namespace :manage do 
  get '/' => 'panel#index', as: :console
  get '/promote' => 'promote#index', as: :promote
  resources :content
  end 
  resources :read
  resources :watch
  get '/guest', to: 'guest#new'
  post '/guest', to: 'guest#create'

 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  video = Watch.new
  @guest = Guest.new
  videos = Watch.limit(4)
  video_info = video.get_youtube_objects(videos)
  @displayed = video.pretty_video_elements(videos, video_info)
  @poems = Read.limit(3)
  end

end

app/helpers/home_helper.rb
module HomeHelper

  
end

app/views/home/index.html.erb
<div class="body">
<center>
<div class="showbox">
  <center>
  <div class="showform">
  <h1>Nothing Short of Good Vibes</h1>
  <%=form_for @guest, :url => guest_path do |f|%>
  <div class="form-group">
    <%= f.text_field :email, placeholder: 'Your email', class: 'ghost-input'%> 
  </div>
  <div class="form-group" >
  <%= f.submit 'Subscribe', class: "showbutton"%>
</div>
  <%end%>
</div>
  </center>
</div>
</center>

<div id="video-section">
<center><h2 class="subtitle">Recent Episodes</h2></center>
<center>
<ul>
  <%@displayed.each do |video|%>
  <li><%= link_to (image_tag(video[1].thumbnail_url, size: "250x250")), watch_path(video[0].id)%></li>
  <%end%>
</ul>
</center>
<%= link_to 'More Videos', watch_index_path, class: 'thumbnail_link'%>
</div>

<div class="categories">
  <center><h2 id="categories">Categories</h2></center>
<%= link_to 'Promotional', watch_index_path(:filter => 'promo'), class: 'ghost1'%>
<%= link_to 'Music Video', watch_index_path(:filter => 'musicvideo'), class: 'ghost2'%>
<%= link_to 'Open Mic', watch_index_path(:filter => 'openmic'), class: 'ghost3'%>
<%= link_to 'Performances', watch_index_path(:filter => 'performance'), class: 'ghost4'%>
</div>



</div>